<?php
/**
 * Report Generator Class - Create markdown reports
 *
 * @package Claude_AI_Scanner
 */

if (!defined('ABSPATH')) {
    exit;
}

class Claude_AI_Report_Generator {
    /**
     * Generate markdown report for Claude Code
     *
     * @param string $scan_type Scan type.
     * @param string $result Analysis result.
     * @param array  $data Raw scan data.
     * @param string $url Optional URL for single URL scans.
     * @return string Markdown content
     */
    public static function generate_markdown($scan_type, $result, $data = [], $url = '') {
        $timestamp = current_time('Y-m-d H:i:s');
        $site_url = home_url();

        $md = "# Claude AI Scanner Report\n\n";
        $md .= "**Generated:** " . $timestamp . "\n";
        $md .= "**Site:** " . esc_url($site_url) . "\n";
        $md .= "**Scan Type:** " . ucfirst(str_replace('-', ' ', $scan_type)) . "\n";

        if ($url) {
            $md .= "**URL Scanned:** " . esc_url($url) . "\n";
        }

        $md .= "\n---\n\n";

        // Instructions for Claude Code
        $md .= "## How to Use This Report\n\n";
        $md .= "1. Open this file in Claude Code\n";
        $md .= "2. Ask Claude to review the issues found\n";
        $md .= "3. Claude can suggest fixes with exact line numbers\n";
        $md .= "4. Use the file paths to navigate to affected code\n\n";

        // Summary section
        $md .= "## Summary\n\n";
        $md .= self::generate_summary_section($scan_type, $data);

        // Issues section
        $md .= "## Issues Found\n\n";
        $md .= self::generate_issues_section($result, $scan_type);

        // Recommendations section
        $md .= "## Recommendations\n\n";
        $md .= self::generate_recommendations_section($result, $scan_type);

        // Code examples section
        $md .= "## Code Examples\n\n";
        $md .= self::generate_code_examples_section($scan_type, $data);

        // Raw analysis
        $md .= "## Full Analysis\n\n";
        $md .= "```\n" . $result . "\n```\n";

        // Footer
        $md .= "\n---\n\n";
        $md .= "*This report was generated by Claude AI Scanner plugin.*\n";
        $md .= "*For more details, visit: " . admin_url('admin.php?page=claude-ai-scanner-dashboard') . "*\n";

        return $md;
    }

    /**
     * Generate summary section
     *
     * @param string $scan_type Scan type.
     * @param array  $data Scan data.
     * @return string
     */
    private static function generate_summary_section($scan_type, $data) {
        $md = "";

        switch ($scan_type) {
            case 'performance':
                $count = count($data);
                $md .= "- **Pages Scanned:** $count\n";
                if ($count > 0) {
                    $times = array_column($data, 'load_time');
                    $avg_time = array_sum($times) / count($times);
                    $md .= "- **Average Load Time:** {$avg_time}s\n";
                }
                break;

            case '404':
                $count = count($data);
                $md .= "- **Broken Links Found:** $count\n";
                $md .= "- **Action Required:** Fix or remove these links\n";
                break;

            case 'seo':
                $count = count($data);
                $md .= "- **Pages Analyzed:** $count\n";
                $good = array_sum(array_map(fn($d) => ($d['quality'] === 'Good') ? 1 : 0, $data));
                $md .= "- **Good SEO:** " . $good . "/" . $count . "\n";
                break;

            case 'redirects':
                $md .= "- **Redirect Configuration Review**\n";
                $md .= "- **Action Required:** Optimize redirect chains\n";
                break;

            case 'single-url':
                $md .= "- **URL:** " . ($data['url'] ?? 'Unknown') . "\n";
                $md .= "- **Load Time:** " . ($data['performance']['load_time'] ?? 'N/A') . "s\n";
                break;
        }

        return $md . "\n";
    }

    /**
     * Generate issues section
     *
     * @param string $result Analysis result.
     * @param string $scan_type Scan type.
     * @return string
     */
    private static function generate_issues_section($result, $scan_type) {
        $md = "";

        // Extract issues from result
        if (preg_match_all('/(?:CRITICAL|HIGH|MEDIUM|⚠️|❌|✓)/i', $result, $matches)) {
            $critical = count(preg_match_all('/CRITICAL/', $result));
            $high = count(preg_match_all('/HIGH/', $result));
            $warnings = count(preg_match_all('/⚠️/', $result));

            if ($critical > 0) {
                $md .= "### 🔴 Critical Issues: $critical\n";
                $md .= "These require immediate attention.\n\n";
            }

            if ($high > 0) {
                $md .= "### 🟠 High Priority: $high\n";
                $md .= "These should be addressed soon.\n\n";
            }

            if ($warnings > 0) {
                $md .= "### 🟡 Warnings: $warnings\n";
                $md .= "These are recommendations for improvement.\n\n";
            }
        }

        return $md ? $md : "No major issues found.\n\n";
    }

    /**
     * Generate recommendations section
     *
     * @param string $result Analysis result.
     * @param string $scan_type Scan type.
     * @return string
     */
    private static function generate_recommendations_section($result, $scan_type) {
        $md = "";

        $recommendations = [
            'performance' => "- Implement caching (object, page, and browser)\n- Optimize images and assets\n- Enable gzip compression\n- Consider a CDN\n",
            '404' => "- Fix broken links by updating URLs\n- Implement 301 redirects for deleted content\n- Add link monitoring\n- Regular content audits\n",
            'seo' => "- Complete meta descriptions for all pages\n- Optimize title tags (50-60 characters)\n- Add structured data (JSON-LD)\n- Improve content depth\n",
            'redirects' => "- Consolidate redirect chains\n- Use 301 for permanent redirects\n- Minimize redirect hops\n- Monitor redirect performance\n",
            'single-url' => "- Focus on identified issues in order\n- Test changes in staging first\n- Monitor performance improvements\n- Rerun scan after fixes\n",
        ];

        $md = $recommendations[$scan_type] ?? "Review the analysis above for specific recommendations.\n";

        return $md . "\n";
    }

    /**
     * Generate code examples section
     *
     * @param string $scan_type Scan type.
     * @param array  $data Scan data.
     * @return string
     */
    private static function generate_code_examples_section($scan_type, $data) {
        $md = "";

        switch ($scan_type) {
            case 'performance':
                $md .= "### Enable Caching in wp-config.php\n\n";
                $md .= "```php\n";
                $md .= "// Enable object caching\n";
                $md .= "define( 'WP_CACHE', true );\n\n";
                $md .= "// Set memory limit for better performance\n";
                $md .= "define( 'WP_MEMORY_LIMIT', '256M' );\n";
                $md .= "```\n\n";
                break;

            case '404':
                $md .= "### Add 301 Redirect in .htaccess\n\n";
                $md .= "```apache\n";
                $md .= "# Redirect old page to new location\n";
                $md .= "Redirect 301 /old-page/ /new-page/\n";
                $md .= "```\n\n";
                break;

            case 'seo':
                $md .= "### Add Meta Tags in Header\n\n";
                $md .= "```html\n";
                $md .= "<meta name=\"description\" content=\"Your page description here\">\n";
                $md .= "<meta name=\"keywords\" content=\"keyword1, keyword2\">\n";
                $md .= "<link rel=\"canonical\" href=\"https://yoursite.com/page/\">\n";
                $md .= "```\n\n";
                break;

            case 'redirects':
                $md .= "### Check Redirect in PHP\n\n";
                $md .= "```php\n";
                $md .= "// Verify redirect is working\n";
                $md .= "\$response = wp_remote_head( \$url, [ 'follow_redirects' => false ] );\n";
                $md .= "\$code = wp_remote_retrieve_response_code( \$response );\n";
                $md .= "echo 'HTTP Status: ' . \$code;\n";
                $md .= "```\n\n";
                break;
        }

        return $md;
    }

    /**
     * Save report to file
     *
     * @param string $scan_type Scan type.
     * @param string $content Markdown content.
     * @return string File path or error
     */
    public static function save_report($scan_type, $content) {
        $upload_dir = wp_upload_dir();
        $reports_dir = $upload_dir['basedir'] . '/claude-ai-scanner-reports';

        // Create reports directory if it doesn't exist
        if (!file_exists($reports_dir)) {
            wp_mkdir_p($reports_dir);
        }

        $filename = 'report-' . $scan_type . '-' . current_time('Y-m-d-His') . '.md';
        $filepath = $reports_dir . '/' . $filename;

        $result = file_put_contents($filepath, $content);

        if ($result === false) {
            return new WP_Error('file_error', 'Could not save report file');
        }

        return $filepath;
    }

    /**
     * Get report download URL
     *
     * @param string $filepath File path.
     * @return string Download URL
     */
    public static function get_report_url($filepath) {
        $upload_dir = wp_upload_dir();
        $relative_path = str_replace($upload_dir['basedir'], '', $filepath);
        return $upload_dir['baseurl'] . $relative_path;
    }

    /**
     * Get list of all reports
     *
     * @return array
     */
    public static function get_reports() {
        $upload_dir = wp_upload_dir();
        $reports_dir = $upload_dir['basedir'] . '/claude-ai-scanner-reports';

        if (!file_exists($reports_dir)) {
            return [];
        }

        $files = scandir($reports_dir);
        $reports = [];

        foreach ($files as $file) {
            if (strpos($file, 'report-') === 0 && strpos($file, '.md') !== false) {
                $filepath = $reports_dir . '/' . $file;
                $reports[] = [
                    'name' => $file,
                    'path' => $filepath,
                    'url' => self::get_report_url($filepath),
                    'date' => filemtime($filepath),
                    'size' => filesize($filepath),
                ];
            }
        }

        // Sort by date descending
        usort($reports, function($a, $b) {
            return $b['date'] - $a['date'];
        });

        return $reports;
    }
}
